### ISSUE TITLE
Add support for matrices

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.recording#1]
See here https://github.com/openworm/OpenWorm/issues/208#issuecomment-42156148

**Comment by gidili** [comment]
@tarelli @jrieke I added [a unit test for matrices](https://github.com/openworm/org.geppetto.recording/blob/435f25f546bd67b92213a2ae4416c746daf335c8/org/geppetto/recording/creators/tests/test_base.py#L58) and it's passing but I am seeing something strange when I look at the recordings file with the HDFViewer.

If the matrices are:

**Step 1**: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
**Step 2**: [[10, 11, 12], [13, 14, 15], [16, 17, 18]]

This is what's in the file according to the viewer:
![screenshot 2015-04-16 19 27 32](https://cloud.githubusercontent.com/assets/68134/7188313/aaad8624-e46e-11e4-90ba-51da1a05ced0.png)

It looks like it's only putting there the first value of each row in the matrix. 

Must be a bug in RecordingCreator.create().

**Comment by gidili** [comment]
This is where the values get set, as you can see the stuff is there as expected but then somehow only the first element of each row makes it into the file:

![screenshot 2015-04-16 19 58 27](https://cloud.githubusercontent.com/assets/68134/7188960/684c2ec0-e473-11e4-9514-5bf70ce86eac.png)

For now the workaround is to probably flatten matrices into a single array.

**Comment by jrieke** [comment]
@gidili As far as I remember, that is simply due to HDFView, which has pretty limited capabilities when visualizing multi dimensional data (the data itself should be there in the file). Let me look into that later and investigate.

**Comment by jrieke** [comment]
Ah yeah, got it: Click on the yellow arrows in HDFView (see below), and you will see the additional dimensions (the order is quite unintuitive, unfortunately, but it really is the same matrix as you entered ;).
![image](https://cloud.githubusercontent.com/assets/5103165/7191048/768a8d80-e43f-11e4-9715-300c6bb49516.png)
(Step 1 and 2 are reversed in that image vs your example)

Also, the dimensions of the data are listed in the field below the table:
![image](https://cloud.githubusercontent.com/assets/5103165/7191096/d122a296-e43f-11e4-9fa5-d49a8a805a72.png)

**Comment by gidili** [comment]
@jrieke ah! Good catch, thanks for looking into this! I added a bunch of unit tests in the process :)

**Comment by jrieke** [comment]
@gidili Ok, great! I also just added a comment in the docstring for add_values to make users aware of that.
